version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://myuser:mypassword@mongo:27017
      - MONGO_DB_NAME=worker-prices
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
